apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghcr-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghcr-app
  template:
    metadata:
      labels:
        app: ghcr-app
    spec:
      containers:
        - name: ghcr-container
          image: ghcr.io/007-bg/kubepythontestapp:latest
          ports:
            - containerPort: 80
